version: '3.8'

networks:
  dev-network:
    driver: bridge

services:
  # Redis for job queue and caching (no auth in dev)
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev-network
    restart: unless-stopped

  # MongoDB database (no auth in dev)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - dev-network
    restart: unless-stopped

  # Backend running in development mode with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads:/app/uploads
      - logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017/webtools
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=dev-secret-key-change-in-production
      - JWT_EXPIRE=7d
    depends_on:
      - redis
      - mongo
    networks:
      - dev-network
    command: npm run dev
    restart: unless-stopped

  # Frontend running in development mode with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - dev-network
    command: npm run dev
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
  uploads:
  logs: 