FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies including dev dependencies
RUN npm install

# Expose port
EXPOSE 5000

# Command to run the app in development mode
CMD ["npm", "run", "dev"] 